name: ⚙️ E2E Test


on:
  workflow_call:
    inputs:
      mainBranch:
        description: Type for main nx affect
        required: false
        default: "master"
        type: string
    secrets:
      NX_CLOUD_ACCESS_TOKEN:
        required: true

env:
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}


jobs:
  e2e-test:
    runs-on: ubuntu-latest
#    services:
#      postgres:
#        image: postgres
#        env:
#          POSTGRES_PASSWORD: postgres
#          POSTGRES_DB: json-api-db
#        options: >-
#          --health-cmd pg_isready
#          --health-interval 10s
#          --health-timeout 5s
#          --health-retries 5
#        ports:
#          - 5432:5432
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: ./.github/actions

      - name: Determine base for NX affected (if not master)
        if: ${{ inputs.mainBranch != 'master' }}
        shell: bash
        run: |
          LAST_TAG=$(git describe --tags --abbrev=0)
          LAST_TAG_HASH=$(git rev-parse "$LAST_TAG")
          CURRENT_COMMIT=$(git rev-parse HEAD)
          echo "Using last tag hash as NX_BASE: $LAST_TAG_HASH"
          echo "Using current commit as NX_HEAD: $CURRENT_COMMIT"
          echo "NX_BASE=$LAST_TAG_HASH" >> $GITHUB_ENV
          echo "NX_HEAD=$CURRENT_COMMIT" >> $GITHUB_ENV

      - name: Determine base for NX affected (if master)
        if: ${{ inputs.mainBranch == 'master' }}
        uses: nrwl/nx-set-shas@v4
        with:
          main-branch-name: ${{ inputs.mainBranch }}

#      - run: npm run typeorm migration:run
#      - run: npm run seed:run
#      - run: npx nx run json-api-server-e2e:e2e --parallel=1
      - run: npx nx run json-api-server-e2e:e2e-micro --parallel=1
